language: node_js
node_js: 12
os: linux
cache: yarn

jobs:
  include:
  - os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - rpm
    deploy:
      - provider: snap
        skip_cleanup: true
        cleanup: false
        snap: dist/*.snap
        channel: beta
        on:
          branch: develop
      - provider: snap
        skip_cleanup: true
        cleanup: false
        snap: dist/*.snap
        channel: stable
        on:
          branch: master
  - os: osx
    osx_image: xcode11.2

branches:
  only:
    - master
    - develop
    - /^hotfix\/.*$/
    - /^release\/.*$/

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - yarn --check-files --production=false
  - export NODE_ENV=production
  - yarn build
  - yarn test
  - |
      if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]
      then
        export CSC_IDENTITY_AUTO_DISCOVERY=false
      fi
  - yarn electron-builder --publish onTagOrDraft --x64
  - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]
      then
        ./dist/mac/Rocket.Chat.app/Contents/MacOS/Rocket.Chat 1>output.log 2>error.log &
        sleep 30
        kill %1
      fi
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]
      then
        ./dist/linux-unpacked/rocketchat-desktop 1>output.log 2>error.log &
        sleep 30
        kill %1
      fi
      cat output.log
      cat error.log
