language: node_js
node_js: 10
os: linux
cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
  - os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - rpm
    deploy:
      - provider: snap
        cleanup: false
        skip_cleanup: true
        snap: dist/*.snap
        channel: beta
        on:
          branch: develop
      - provider: snap
        cleanup: false
        skip_cleanup: true
        snap: dist/*.snap
        channel: stable
        on:
          branch: master
  - os: osx
    osx_image: xcode11.2

branches:
  only:
    - master
    - develop
    - /^hotfix\/.*$/
    - /^release\/.*$/

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - yarn --check-files
  - yarn test

script:
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then export CSC_IDENTITY_AUTO_DISCOVERY=false; fi
  - NODE_ENV=production yarn release
